"""Reference register. Every [Rn] citation in the document must resolve here."""

PD = "https://docs.pega.com/bundle/platform/page/platform/"
PD25 = "https://docs.pega.com/bundle/platform-25/page/platform/"
GH = "https://github.com/pegasystems/pega-helm-charts/blob/master/"
CC = "https://docs.confluent.io/cloud/current/"
OS = "https://docs.opensearch.org/latest/"
OK = "https://developer.okta.com/docs/"

REFS = {
    "R1": ("Pega Documentation", "Platform Support Guide, Pega Platform '26", PD + "deployment/platform-support-guide/platform-support-guide.html"),
    "R2": ("Pega Documentation", "Adopting Pega Platform infrastructure changes", PD + "deployment/adopting-infrastructure-changes.html"),
    "R3": ("Pega Documentation", "Completing prerequisites to update to Pega Platform '26", PD + "deployment/client-managed-cloud/prereq-pega-platform-26.html"),
    "R4": ("Pega Documentation", "Prerequisites for Pega Platform '25", PD + "deployment/client-managed-cloud/prereq-pega-platform-25.html"),
    "R5": ("Pega Documentation", "Removing Hazelcast from your deployment", PD + "deployment/externalization-of-services/removing-hazelcast.html"),
    "R6": ("Pega Documentation", "Performing prerequisite steps (Hazelcast removal)", PD25 + "deployment/externalization-of-services/hz-removal-prereq.html"),
    "R7": ("Pega Documentation", "Removing Hazelcast FAQ", PD25 + "deployment/externalization-of-services/removing-hazelcast-faq.html"),
    "R8": ("Pega Documentation", "Configuring a prpcUtils streaming service", PD + "deployment/client-managed-cloud/configuring-prpcutils-streaming.html"),
    "R9": ("Pega Documentation", "Updating Pega Platform to Tomcat 10.1", PD + "deployment/tomcat-10-prepare-overview.html"),
    "R10": ("Pega Documentation", "Create primary key constraints for tables in your database (primaryKeyUtility)", PD + "deployment/run-primarykeyutility.html"),
    "R11": ("Pega Documentation", "External Kafka in your deployment", PD + "deployment/externalization-of-services/externalize-kafka-in-your-deployment.html"),
    "R12": ("Pega Documentation", "Configuring a containerized deployment to use a Kafka service", PD + "deployment/externalization-of-services/deploy-external-kafka.html"),
    "R13": ("Pega Documentation", "Switching Kafka providers while preserving Stream data", PD + "deployment/externalization-of-services/migrate-external-kafka-providers.html"),
    "R14": ("Pega Documentation", "External Search in your deployment", PD + "deployment/externalization-of-services/externalize-search-in-your-deployment.html"),
    "R15": ("Pega Documentation", "Connecting Pega Platform to SRS", PD + "deployment/externalization-of-services/connect-pega-platform-to-srs.html"),
    "R16": ("Pega Documentation", "Connecting a new containerized deployment to SRS", PD + "deployment/externalization-of-services/connect-new-k8s-to-srs.html"),
    "R17": ("Pega Documentation", "Rebuilding search indexes", PD + "search-engine/rebuilding-search-indexes.html"),
    "R18": ("Pega Documentation", "Indexing of data", PD + "search-engine/indexing-data.html"),
    "R19": ("Pega Documentation", "Checking search index status", PD + "search-engine/search-index-status-checking.html"),
    "R20": ("Pega Documentation", "Meeting requirements and prerequisites (client-managed cloud)", PD + "deployment/client-managed-cloud/requirements-prerequisites.html"),
    "R21": ("Pega Documentation", "Understanding the Pega Platform deployment architecture", PD + "deployment/client-managed-cloud/pega-kubernetes-architecture.html"),
    "R22": ("Pega Documentation", "Third-party externalized services FAQs", PD + "deployment/client-managed-cloud/third-party-externalized-services-faqs.html"),
    "R23": ("Pegasystems, GitHub", "Pega Helm charts: charts/pega/README.md (chart 4.13.0)", GH + "charts/pega/README.md"),
    "R24": ("Pegasystems, GitHub", "Pega Helm charts: backingservices SRS chart README", GH + "charts/backingservices/charts/srs/README.md"),
    "R25": ("Pegasystems, GitHub", "Pega Helm charts: Switch from embedded Stream to externalized Kafka service", GH + "charts/pega/MigrationToExternalStream.md"),
    "R26": ("Pegasystems, GitHub", "Pega Helm charts: Kafka cluster requirements", GH + "charts/pega/KafkaClusterRequirement.md"),
    "R27": ("Pegasystems, GitHub", "Pega Helm charts: Deploying Pega Platform on AKS", GH + "docs/Deploying-Pega-on-AKS.md"),
    "R28": ("Pega Academy", "Search and Reporting Service", "https://academy.pega.com/topic/search-and-reporting-service/v3"),
    "R29": ("Pega Academy", "Deployment architecture with external services", "https://academy.pega.com/topic/deployment-architecture-external-services/v1"),
    "R30": ("Pega Academy", "Cloud deployment architecture", "https://academy.pega.com/topic/cloud-deployment-architecture/v1"),
    "R31": ("Confluent Documentation", "Kafka cluster types in Confluent Cloud", CC + "clusters/cluster-types.html"),
    "R32": ("Confluent Documentation", "Use Azure Private Link for Dedicated clusters on Confluent Cloud", CC + "networking/private-links/azure-privatelink.html"),
    "R33": ("Confluent Documentation", "Configuration reference for topics in Confluent Cloud", CC + "client-apps/topics/manage.html"),
    "R34": ("Confluent Documentation", "Kafka cluster configuration (editable broker settings)", CC + "clusters/broker-config.html"),
    "R35": ("Confluent Documentation", "Geo-replication with Cluster Linking on Confluent Cloud", CC + "multi-cloud/cluster-linking/index.html"),
    "R36": ("Confluent Documentation", "Multi-tenancy and client quotas on Confluent Cloud", CC + "clusters/client-quotas.html"),
    "R37": ("OpenSearch Documentation", "Creating a cluster", OS + "tuning-your-cluster/index/"),
    "R38": ("OpenSearch Documentation", "Snapshot and restore for migration", OS + "migrate-or-upgrade/snapshot-restore/"),
    "R39": ("OpenSearch Documentation", "Is Migration Assistant right for you? (supported migration paths)", OS + "migration-assistant/is-migration-assistant-right-for-you/"),
    "R40": ("OpenSearch Documentation", "Defining users and roles", OS + "security/access-control/users-roles/"),
    "R41": ("OpenSearch Documentation", "Security permissions", OS + "security/access-control/permissions/"),
    "R42": ("Okta Developer", "Authorization servers", OK + "concepts/auth-servers/"),
    "R43": ("Okta Developer", "Implement authorization by grant type: client credentials", OK + "guides/implement-grant-type/clientcreds/main/"),
    "R44": ("Okta Developer", "Customize tokens returned from Okta with custom claims", OK + "guides/customize-tokens-returned-from-okta/main/"),
    "R45": ("Okta Developer", "Client authentication methods", OK + "api/openapi/okta-oauth/guides/client-auth/"),
    "R46": ("Okta Developer", "Okta Expression Language overview guide", OK + "reference/okta-expression-language/"),
    "R47": ("Microsoft Learn", "Azure Private Endpoint DNS configuration", "https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns"),
    "R48": ("External Secrets Operator", "Azure Key Vault provider", "https://external-secrets.io/latest/provider/azure-key-vault/"),
    "R49": ("Pega Documentation", "Changing the default number of partitions per topic", "https://docs.pega.com/bundle/platform-241/page/platform/deployment/embedded-kafka-cassandra/change-default-partitions-count-stream-nodes.html"),
    "R50": ("Pega Documentation", "Creating a Queue Processor rule ('25)", PD25 + "background-processing/queue-processor-create-rule.html"),
    "R51": ("Pega Documentation", "Configuring Pega Diagnostic Center for on-premises systems", "https://docs.pega.com/bundle/pega-diagnostic-center/page/pega-diagnostic-center/guide/configuring-on-premises-systems.html"),
    "R52": ("Okta Developer", "Rate limits overview", OK + "reference/rate-limits/"),
    "R53": ("Okta Developer", "Key rotation", OK + "concepts/key-rotation/"),
    "R54": ("Amazon OpenSearch Service Developer Guide", "Sizing domains: storage requirements", "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/bp-storage.html"),
    "R55": ("Amazon OpenSearch Service Developer Guide", "Shard strategy", "https://docs.aws.amazon.com/opensearch-service/latest/developerguide/bp-sharding.html"),
    "R56": ("Confluent Documentation", "Confluent Cloud Metrics API", CC + "monitoring/metrics-api.html"),
    "R57": ("Confluent Documentation", "Audit log concepts on Confluent Cloud", CC + "monitoring/audit-logging/cloud-audit-log-concepts.html"),
    "R58": ("OpenSearch Documentation", "Logs (slow logs, task logs, deprecation logs)", OS + "install-and-configure/configuring-opensearch/logs/"),
    "R59": ("Microsoft Learn", "Availability zones in Azure Kubernetes Service", "https://learn.microsoft.com/en-us/azure/aks/availability-zones"),
    "R60": ("Microsoft Learn", "Kubernetes monitoring in Azure Monitor", "https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-overview"),
    "R61": ("Pegasystems, GitHub", "Pega Helm charts: pega deployment template (chart 4.13.0)", GH + "charts/pega/templates/_pega-deployment.tpl"),
    "R62": ("Pegasystems, GitHub", "Pega Helm charts: SRS network policy and service templates", GH + "charts/backingservices/charts/srs/templates/srsservice_networkpolicy.yaml"),
    "R63": ("Pegasystems, GitHub", "Pega Helm charts: Recommended JVM arguments", GH + "charts/pega/RecommendedJVMArgs.md"),
    "R64": ("Pega Documentation", "Queue-For-Processing method (snapshot option, broken queue)", "https://docs.pega.com/bundle/platform-241/page/platform/background-processing/queue-processing-method.html"),
    "R65": ("Pega Documentation", "Queue processing at run time", PD + "background-processing/queue-processors-how-work.html"),
    "R66": ("Pega Academy", "Queue processors and job schedulers", "https://academy.pega.com/topic/queue-processors-and-job-schedulers/v4"),
    "R67": ("Pega Documentation", "Custom search properties", PD + "search-engine/custom-search-properties.html"),
    "R68": ("Pega Documentation", "Compatibility of search engines upon migration ('24.1)", "https://docs.pega.com/bundle/platform-241/page/platform/search-engine/compatibility-search-engines.html"),
    "R69": ("Pega Documentation", "Reindexing errors", PD + "search-engine/reindexing-errors.html"),
    "R70": ("Pega Documentation", "Migrating from embedded Elasticsearch to SRS ('24.2)", "https://docs.pega.com/bundle/platform-242/page/platform/deployment/client-managed-cloud/migrate-to-srs-overview.html"),
    "R71": ("Pega Documentation", "Encryption ('25)", PD25 + "security/encryption.html"),
    "R72": ("Pega Documentation", "Configuring a Microsoft Azure Key Vault keystore", PD + "security/configure-microsoft-azure-key-vault-keystore.html"),
    "R73": ("Confluent Documentation", "Protect data at rest using self-managed encryption keys", CC + "security/encrypt/byok/overview.html"),
    "R74": ("Confluent Documentation", "Use self-managed encryption keys on Azure", CC + "security/encrypt/byok/byok-azure.html"),
    "R75": ("Confluent Documentation", "Manage data in transit with TLS on Confluent Cloud", CC + "security/encrypt/tls.html"),
    "R76": ("OpenSearch Documentation", "Configuring TLS certificates", OS + "security/configuration/tls/"),
    "R77": ("OpenSearch Documentation", "Audit logs", OS + "security/audit-logs/index/"),
    "R78": ("Microsoft Learn", "Enable host-based encryption on Azure Kubernetes Service", "https://learn.microsoft.com/en-us/azure/aks/enable-host-encryption"),
    "R79": ("Microsoft Learn", "Bring your own keys (BYOK) with Azure managed disks in AKS", "https://learn.microsoft.com/en-us/azure/aks/azure-disk-customer-managed-keys"),
    "R80": ("Microsoft Learn", "Log Analytics workspace data export in Azure Monitor", "https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export"),
    "R81": ("Okta Help Center", "Log streaming", "https://help.okta.com/en-us/content/topics/reports/log-streaming/about-log-streams.htm"),
    "R82": ("Okta Developer", "System Log API", "https://developer.okta.com/docs/api/openapi/okta-management/management/tag/SystemLog/"),
}
